# Generated by Django 5.2.11 on 2026-02-20 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='requests.category', verbose_name='Категорії допомоги'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
