# Generated by Django 5.2.17 on 2026-09-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
