# Generated by Django 5.2.17 on 2026-09-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Вхід без пароля кнопкою на сторінці входу, коли DEMO_MODE увімкнено.', verbose_name='Демо-акаунт'),
        ),
    ]
