# Generated by Django 5.2.17 on 2026-09-24 19:18

from django.db import migrations, models


def trust_existing_users(apps, schema_editor):
    """Accounts created before email confirmation existed keep their access (L1)."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(email_verified_at__isnull=True).update(email_verified_at=models.F("created_at"))


def create_moderators_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Модератори")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email підтверджено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Перевірений'),
        ),
        migrations.RunPython(trust_existing_users, migrations.RunPython.noop),
        migrations.RunPython(create_moderators_group, migrations.RunPython.noop),
    ]
