# Generated by Django 5.2.17 on 2026-09-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Згода з правилами'),
        ),
    ]
