# Generated by Django 5.2.17 on 2026-09-24 19:23

import apps.moderation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.moderation.models._generate_code, max_length=20, unique=True, verbose_name='Код')),
                ('organization', models.CharField(max_length=150, verbose_name='Організація')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Максимум використань')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='Використано')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Діє до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Код організації',
                'verbose_name_plural': 'Коди організацій',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(choices=[('fraud', 'Шахрайство або обман'), ('unsafe', 'Небезпечна ситуація'), ('offensive', 'Образи чи неприйнятна поведінка'), ('spam', 'Спам або реклама'), ('false_info', 'Неправдива інформація'), ('other', 'Інше')], max_length=15, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('open', 'Нова'), ('resolved', 'Вжито заходів'), ('dismissed', 'Відхилено')], default='open', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подано')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Розглянуто')),
                ('resolution', models.CharField(blank=True, max_length=500, verbose_name='Рішення')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Автор скарги')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Розглянув')),
            ],
            options={
                'verbose_name': 'Скарга',
                'verbose_name_plural': 'Скарги',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='moderation__content_408935_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('reporter', 'content_type', 'object_id'), name='one_open_report_per_target')],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Схвалено'), ('rejected', 'Відхилено'), ('revoked', 'Відкликано')], default='pending', max_length=10, verbose_name='Статус')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('about', models.TextField(max_length=1500, verbose_name='Розкажіть про себе')),
                ('contact_link', models.URLField(blank=True, verbose_name='Соцмережа або сторінка організації')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Організація')),
                ('video_call_ok', models.BooleanField(default=False, verbose_name='Готовий(а) до короткого відеодзвінка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подано')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Розглянуто')),
                ('decision_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина рішення')),
                ('invite_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='moderation.invitecode', verbose_name='Код організації')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Розглянув')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Заявка на перевірку',
                'verbose_name_plural': 'Заявки на перевірку',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='one_pending_verification_per_user')],
            },
        ),
    ]
