# Generated by Django 5.2.17 on 2026-09-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='video_call_ok',
            field=models.BooleanField(default=False, verbose_name='Можу поспілкуватися коротким відеодзвінком'),
        ),
    ]
