# Generated by Django 5.2.11 on 2026-02-20 15:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-ідентифікатор')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='CSS-клас іконки')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('urgency', models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока'), ('critical', 'Критична')], default='medium', max_length=10, verbose_name='Терміновість')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('in_progress', 'В процесі'), ('completed', 'Виконано'), ('cancelled', 'Скасовано'), ('expired', 'Прострочено')], default='active', max_length=15, verbose_name='Статус')),
                ('needed_date', models.DateTimeField(verbose_name='Дата та час допомоги')),
                ('duration', models.CharField(choices=[('15min', '15 хвилин'), ('30min', '30 хвилин'), ('1h', '1 година'), ('2h+', '2 години+')], default='1h', max_length=10, verbose_name='Тривалість')),
                ('volunteers_needed', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Кількість волонтерів')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Довгота')),
                ('photo', models.ImageField(blank=True, upload_to='requests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests', to='requests.category', verbose_name='Категорія')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач')),
            ],
            options={
                'verbose_name': 'Запит допомоги',
                'verbose_name_plural': 'Запити допомоги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('accepted', 'Прийнято'), ('rejected', 'Відхилено')], default='pending', max_length=10, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата відгуку')),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='requests.helprequest', verbose_name='Запит')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_responses', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Відгук волонтера',
                'verbose_name_plural': 'Відгуки волонтерів',
                'ordering': ['-created_at'],
                'unique_together': {('help_request', 'volunteer')},
            },
        ),
    ]
