# Generated by Django 5.2.17 on 2026-09-24 19:02

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Нагадування надіслано'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Статус змінено'),
        ),
        migrations.AddField(
            model_name='response',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Позначено виконаним'),
        ),
        migrations.AddField(
            model_name='response',
            name='status_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='Причина зміни статусу'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Довгота'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('in_progress', 'В процесі'), ('awaiting_confirmation', 'Очікує підтвердження'), ('completed', 'Виконано'), ('cancelled', 'Скасовано'), ('expired', 'Прострочено')], default='active', max_length=25, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('accepted', 'Прийнято'), ('rejected', 'Відхилено'), ('withdrawn', 'Волонтер вийшов'), ('removed', 'Знято отримувачем'), ('closed', 'Набір закрито')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['status', 'needed_date'], name='requests_he_status_784081_idx'),
        ),
    ]
