# Generated by Django 5.2.17 on 2026-09-24 19:19

from django.db import migrations, models


def backfill_published(apps, schema_editor):
    """Everything that was ever public counts as published (skips premoderation)."""
    HelpRequest = apps.get_model("requests", "HelpRequest")
    HelpRequest.objects.filter(published_at__isnull=True).update(published_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_backfill_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='help_format',
            field=models.CharField(choices=[('home_visit', 'Візит додому'), ('doorstep', 'Під двері'), ('public_place', 'Зустріч у публічному місці'), ('remote', 'Онлайн або телефоном')], default='home_visit', max_length=15, verbose_name='Формат допомоги'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='Коментар модератора'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('pending_moderation', 'На модерації'), ('rejected', 'Відхилено модератором'), ('active', 'Активний'), ('in_progress', 'В процесі'), ('awaiting_confirmation', 'Очікує підтвердження'), ('completed', 'Виконано'), ('cancelled', 'Скасовано'), ('expired', 'Прострочено')], default='active', max_length=25, verbose_name='Статус'),
        ),
        migrations.RunPython(backfill_published, migrations.RunPython.noop),
    ]
