# Generated by Django 5.2.17 on 2026-09-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_help_format_moderation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helprequest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Запит допомоги', 'verbose_name_plural': 'Запити допомоги'},
        ),
    ]
