# Generated by Django 5.2.17 on 2026-09-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_ordering_tiebreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Кому допомагаємо (ім'я)"),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='beneficiary_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон цієї людини'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='on_behalf',
            field=models.BooleanField(default=False, verbose_name='Подаю від імені іншої людини'),
        ),
    ]
