# Generated by Django 5.2.17 on 2026-09-24 20:06

from django.db import migrations, models


def city_from_address(apps, schema_editor):
    """Best guess for existing requests: a short first part like "Київ, вул. ..." ."""
    HelpRequest = apps.get_model("requests", "HelpRequest")
    for help_request in HelpRequest.objects.filter(city="").exclude(address=""):
        first = help_request.address.split(",")[0].strip()
        if first and len(first) <= 30 and not any(ch.isdigit() for ch in first):
            help_request.city = first
            help_request.save(update_fields=["city"])


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_on_behalf'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто або село'),
        ),
        migrations.RunPython(city_from_address, migrations.RunPython.noop),
    ]
