# Generated by Django 5.2.17 on 2026-09-24 20:32

import django.utils.timezone
from django.db import migrations, models


def from_request(apps, schema_editor):
    """Closed responses of existing data: best guess is the request's last status change."""
    Response = apps.get_model("requests", "Response")
    for response in Response.objects.exclude(status="pending").select_related("help_request"):
        response.status_changed_at = response.help_request.status_changed_at
        response.save(update_fields=["status_changed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_public_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Статус змінено'),
        ),
        migrations.RunPython(from_request, migrations.RunPython.noop),
    ]
