# Generated by Django 5.2.17 on 2026-09-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_category_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('pending_moderation', 'На модерації'), ('rejected', 'Відхилено модератором'), ('active', 'Шукає волонтерів'), ('in_progress', 'У процесі'), ('awaiting_confirmation', 'Чекає підтвердження'), ('completed', 'Виконано'), ('cancelled', 'Скасовано'), ('expired', 'Прострочено')], default='active', max_length=25, verbose_name='Статус'),
        ),
    ]
