# Generated by Django 5.2.17 on 2026-09-24 19:11

from django.conf import settings
from django.db import migrations, models


def publish_existing(apps, schema_editor):
    """Reviews written before blind exchange existed were already public."""
    Review = apps.get_model("reviews", "Review")
    Review.objects.filter(published_at__isnull=True).update(published_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_lifecycle'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оцінка', 'verbose_name_plural': 'Оцінки'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубліковано'),
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Коментар'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'target', 'help_request'), name='one_review_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_1_to_5'),
        ),
        migrations.RunPython(publish_existing, migrations.RunPython.noop),
    ]
