# Generated by Django 5.2.17 on 2026-09-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_two_sided_blind'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Приховано модератором'),
        ),
    ]
