# Generated by Django 5.2.11 on 2026-04-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Сповіщення', 'verbose_name_plural': 'Сповіщення'},
        ),
    ]
