# Generated by Django 5.2.17 on 2026-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_more_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_response', 'Новий відгук волонтера'), ('volunteer_withdrew', 'Волонтер вийшов'), ('marked_done', 'Волонтер позначив виконаним'), ('request_accepted', 'Вас прийнято'), ('request_rejected', 'Відгук відхилено'), ('response_closed', 'Набір закрито'), ('volunteer_removed', 'Вас знято із запиту'), ('completion_disputed', 'Виконання не підтверджено'), ('new_nearby_request', 'Новий запит поблизу'), ('request_completed', 'Запит виконано'), ('request_cancelled', 'Запит скасовано'), ('request_expired', 'Запит прострочено'), ('reminder', 'Нагадування'), ('new_review', 'Нова оцінка'), ('review_reminder', 'Нагадування про оцінку')], max_length=25, verbose_name='Тип'),
        ),
    ]
