# Generated by Django 5.2.17 on 2026-09-24 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.BooleanField(default=True, verbose_name='Відгуки волонтерів і рішення щодо них')),
                ('lifecycle', models.BooleanField(default=True, verbose_name='Зміни запиту: виконано, скасовано, нагадування')),
                ('messages', models.BooleanField(default=True, verbose_name='Нові повідомлення в розмовах')),
                ('reviews', models.BooleanField(default=True, verbose_name='Оцінки')),
                ('nearby', models.BooleanField(default=False, verbose_name='Нові запити поблизу')),
                ('account', models.BooleanField(default=True, verbose_name='Перевірка профілю та рішення модераторів')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Налаштування email',
                'verbose_name_plural': 'Налаштування email',
            },
        ),
    ]
