# Generated by Django 5.2.17 on 2026-09-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_email_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=300, verbose_name='Посилання'),
        ),
    ]
