# Generated by Django 5.2.17 on 2026-09-24 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0006_on_behalf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Останнє повідомлення')),
                ('recipient_read_at', models.DateTimeField(blank=True, null=True)),
                ('volunteer_read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_notified_at', models.DateTimeField(blank=True, null=True)),
                ('volunteer_notified_at', models.DateTimeField(blank=True, null=True)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='requests.helprequest', verbose_name='Запит')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Розмова',
                'verbose_name_plural': 'Розмови',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Повідомлення'), ('phone', 'Номер телефону'), ('system', 'Системне')], default='text', max_length=10, verbose_name='Тип')),
                ('body', models.TextField(max_length=1000, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Надіслано')),
                ('hidden_at', models.DateTimeField(blank=True, null=True, verbose_name='Приховано модератором')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation', verbose_name='Розмова')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('help_request', 'volunteer'), name='one_conversation_per_volunteer'),
        ),
    ]
